version: '3.9'

services:
  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gittrends.app
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
