version: '3.9'

services:
  postgres:
    image: postgres:alpine
    command: postgres -c 'max_connections=500'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gittrends.app
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
