version: '3.9'

services:
  redis:
    image: redis:alpine
    command: --maxmemory-policy noeviction
    restart: unless-stopped
    ports:
      - 6379:6379

  memcached:
    image: memcached:alpine
    command: -m 128 -p 11211 -vv
    restart: unless-stopped
    ports:
      - 11211:11211

  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-gittrends.app}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 5433:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  db:
    driver: local
