version: '3.9'

services:
  redis:
    image: redis:alpine
    command: --maxmemory-policy noeviction
    restart: unless-stopped
    ports:
      - 6379:6379

  cache:
    build:
      context: ..
      dockerfile: deployments/cache/Dockerfile
    restart: unless-stopped
    command: yarn start --type memory --cache-size ${CACHE_SIZE:-128}
    ports:
      - 6380:80

  postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${NODE_ENV:-dev}.${POSTGRES_DB:-gittrends.app}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 5433:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  proxy:
    build:
      context: ..
      dockerfile: deployments/github-proxy-server/Dockerfile
    restart: unless-stopped
    command: --tokens /tokens.txt
    environment:
      PORT: 80
      GPS_REQUEST_INTERVAL: ${GPS_REQUEST_INTERVAL:-100}
      GPS_REQUEST_TIMEOUT: ${GPS_REQUEST_TIMEOUT:-30000}
      GPS_MIN_REMAINING: ${GPS_MIN_REMAINING:-100}
    ports:
      - 3000:80
    volumes:
      - ../tokens.${NODE_ENV:-development}.txt:/tokens.txt:ro

  cli:
    build:
      context: ..
      dockerfile: deployments/cli/Dockerfile
    restart: unless-stopped
    command: yarn cli-runtime bull-board --threads ${CLI_THREADS:-0} --workers ${CLI_WORKERS:-0}
    environment:
      CLI_API_URL: http://proxy:80
      CLI_DATABASE: postgres
      CLI_DATABASE_HOST: postgres
      CLI_DATABASE_PORT: 5432
      CLI_DATABASE_USERNAME: ${POSTGRES_USER:-root}
      CLI_DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-root}
      CLI_DATABASE_DB: ${NODE_ENV:-dev}.${POSTGRES_DB:-gittrends.app}
      CLI_DATABASE_POOL_MIN: ${CLI_DATABASE_POOL_MIN:-1}
      CLI_DATABASE_POOL_MAX: ${CLI_DATABASE_POOL_MAX:-3}
      CLI_REDIS_HOST: redis
      CLI_REDIS_PORT: 6379
      CLI_REDIS_DB: 0
      CLI_CACHE_HOST: cache
      CLI_CACHE_PORT: 80
      CLI_UPDATER_ITERATIONS: ${CLI_UPDATER_ITERATIONS:-3}
    ports:
      - 8080:80
    depends_on:
      - postgres
      - redis
      - cache
      - proxy

volumes:
  db:
    driver: local
