/* *  Author: Hudson S. Borges */
import { z } from 'zod';

import { ActorSchema } from './Actor';

export const RepositorySchema = z.object({
  id: z.string(),
  assignable_users: z.number().optional(),
  code_of_conduct: z.string().optional(),
  created_at: z.date().optional(),
  database_id: z.number().optional(),
  default_branch: z.string().optional(),
  delete_branch_on_merge: z.boolean().optional(),
  description: z.string().optional(),
  disk_usage: z.number().optional(),
  forks: z.number().optional(),
  funding_links: z.array(z.object({ url: z.string(), platform: z.string().optional() })).optional(),
  has_issues_enabled: z.boolean().optional(),
  has_projects_enabled: z.boolean().optional(),
  has_wiki_enabled: z.boolean().optional(),
  homepage_url: z.string().optional(),
  is_archived: z.boolean().optional(),
  is_blank_issues_enabled: z.boolean().optional(),
  is_disabled: z.boolean().optional(),
  is_empty: z.boolean().optional(),
  is_fork: z.boolean().optional(),
  is_in_organization: z.boolean().optional(),
  is_locked: z.boolean().optional(),
  is_mirror: z.boolean().optional(),
  is_private: z.boolean().optional(),
  is_security_policy_enabled: z.boolean().optional(),
  is_template: z.boolean().optional(),
  is_user_configuration_repository: z.boolean().optional(),
  issues: z.number().optional(),
  labels: z.number().optional(),
  languages: z.array(z.object({ language: z.string(), size: z.number() })).optional(),
  license_info: z.string().optional(),
  lock_reason: z.string().optional(),
  mentionable_users: z.number().optional(),
  merge_commit_allowed: z.boolean().optional(),
  milestones: z.number().optional(),
  mirror_url: z.string().optional(),
  name: z.string().optional(),
  name_with_owner: z.string(),
  open_graph_image_url: z.string().optional(),
  owner: z.union([z.string(), ActorSchema]).optional(),
  parent: z.string().optional(),
  primary_language: z.string().optional(),
  pushed_at: z.date().optional(),
  pull_requests: z.number().optional(),
  rebase_merge_allowed: z.boolean().optional(),
  releases: z.number().optional(),
  repository_topics: z.array(z.string()).optional(),
  squash_merge_allowed: z.boolean().optional(),
  stargazers: z.number().optional(),
  tags: z.number().optional(),
  template_repository: z.string().optional(),
  updated_at: z.date().optional(),
  url: z.string().optional(),
  uses_custom_open_graph_image: z.boolean().optional(),
  vulnerability_alerts: z.number().optional(),
  watchers: z.number().optional(),
});

export type Repository = z.infer<typeof RepositorySchema>;
